onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -group tb_baseboard /tb_baseboard/i
add wave -noupdate -group tb_baseboard /tb_baseboard/clk
add wave -noupdate -group tb_baseboard /tb_baseboard/rstn
add wave -noupdate -group tb_baseboard /tb_baseboard/i2c_wr
add wave -noupdate -group tb_baseboard /tb_baseboard/i2c_address
add wave -noupdate -group tb_baseboard /tb_baseboard/i2c_wrdata1
add wave -noupdate -group tb_baseboard /tb_baseboard/i2c_wrdata2
add wave -noupdate -group tb_baseboard /tb_baseboard/i2c_wrdata3
add wave -noupdate -group tb_baseboard /tb_baseboard/i2c_data_num
add wave -noupdate -group tb_baseboard /tb_baseboard/adr
add wave -noupdate -group tb_baseboard /tb_baseboard/dat_o
add wave -noupdate -group tb_baseboard /tb_baseboard/dat0_i
add wave -noupdate -group tb_baseboard /tb_baseboard/cyc
add wave -noupdate -group tb_baseboard /tb_baseboard/stb
add wave -noupdate -group tb_baseboard /tb_baseboard/we
add wave -noupdate -group tb_baseboard /tb_baseboard/ack
add wave -noupdate -group tb_baseboard /tb_baseboard/scl
add wave -noupdate -group tb_baseboard /tb_baseboard/sda
add wave -noupdate -group tb_baseboard /tb_baseboard/porta
add wave -noupdate -group tb_baseboard /tb_baseboard/portb
add wave -noupdate -group tb_baseboard /tb_baseboard/PORT_CS
add wave -noupdate -group tb_baseboard /tb_baseboard/OFFSET_SEL
add wave -noupdate -group tb_baseboard /tb_baseboard/I2C_DOUT
add wave -noupdate -group tb_baseboard /tb_baseboard/RD_WR
add wave -noupdate -group tb_baseboard /tb_baseboard/DIN_0
add wave -noupdate -group tb_baseboard /tb_baseboard/i2c_busy
add wave -noupdate -group tb_baseboard /tb_baseboard/i2c_rddata1
add wave -noupdate -group tb_baseboard /tb_baseboard/i2c_rddata2
add wave -noupdate -group tb_baseboard /tb_baseboard/DRV_ACT
add wave -noupdate -group tb_baseboard /tb_baseboard/SGPIO_CK
add wave -noupdate -group tb_baseboard /tb_baseboard/SGPIO_LD
add wave -noupdate -group tb_baseboard /tb_baseboard/SGPIO_DATA
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/SYSCLK
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/RESET_N
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/SCL
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/SDA
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV3_ACT_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV2_ACT_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV1_ACT_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV0_ACT_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV7_ACT_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV6_ACT_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV5_ACT_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV4_ACT_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV11_ACT_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV10_ACT_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV9_ACT_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV8_ACT_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV15_ACT_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV14_ACT_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV13_ACT_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV12_ACT_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV19_ACT_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV18_ACT_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV17_ACT_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV16_ACT_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV23_ACT_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV22_ACT_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV21_ACT_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV20_ACT_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV27_ACT_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV26_ACT_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV25_ACT_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV24_ACT_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV31_ACT_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV30_ACT_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV29_ACT_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV28_ACT_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV35_ACT_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV34_ACT_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV33_ACT_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV32_ACT_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV3_PWR_EN_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV2_PWR_EN_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV1_PWR_EN_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV0_PWR_EN_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV7_PWR_EN_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV6_PWR_EN_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV5_PWR_EN_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV4_PWR_EN_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV11_PWR_EN_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV10_PWR_EN_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV9_PWR_EN_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV8_PWR_EN_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV15_PWR_EN_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV14_PWR_EN_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV13_PWR_EN_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV12_PWR_EN_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV19_PWR_EN_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV18_PWR_EN_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV17_PWR_EN_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV16_PWR_EN_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV23_PWR_EN_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV22_PWR_EN_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV21_PWR_EN_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV20_PWR_EN_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV27_PWR_EN_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV26_PWR_EN_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV25_PWR_EN_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV24_PWR_EN_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV31_PWR_EN_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV30_PWR_EN_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV29_PWR_EN_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV28_PWR_EN_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV35_PWR_EN_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV34_PWR_EN_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV33_PWR_EN_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV32_PWR_EN_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV3_PWROK
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV2_PWROK
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV1_PWROK
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV0_PWROK
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV7_PWROK
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV6_PWROK
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV5_PWROK
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV4_PWROK
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV11_PWROK
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV10_PWROK
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV9_PWROK
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV8_PWROK
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV15_PWROK
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV14_PWROK
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV13_PWROK
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV12_PWROK
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV19_PWROK
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV18_PWROK
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV17_PWROK
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV16_PWROK
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV23_PWROK
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV22_PWROK
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV21_PWROK
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV20_PWROK
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV27_PWROK
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV26_PWROK
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV25_PWROK
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV24_PWROK
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV31_PWROK
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV30_PWROK
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV29_PWROK
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV28_PWROK
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV35_PWROK
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV34_PWROK
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV33_PWROK
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV32_PWROK
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV3_PRSNT_AMBER_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV2_PRSNT_AMBER_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV1_PRSNT_AMBER_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV0_PRSNT_AMBER_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV7_PRSNT_AMBER_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV6_PRSNT_AMBER_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV5_PRSNT_AMBER_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV4_PRSNT_AMBER_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV11_PRSNT_AMBER_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV10_PRSNT_AMBER_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV9_PRSNT_AMBER_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV8_PRSNT_AMBER_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV15_PRSNT_AMBER_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV14_PRSNT_AMBER_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV13_PRSNT_AMBER_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV12_PRSNT_AMBER_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV19_PRSNT_AMBER_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV18_PRSNT_AMBER_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV17_PRSNT_AMBER_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV16_PRSNT_AMBER_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV23_PRSNT_AMBER_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV22_PRSNT_AMBER_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV21_PRSNT_AMBER_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV20_PRSNT_AMBER_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV27_PRSNT_AMBER_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV26_PRSNT_AMBER_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV25_PRSNT_AMBER_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV24_PRSNT_AMBER_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV31_PRSNT_AMBER_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV30_PRSNT_AMBER_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV29_PRSNT_AMBER_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV28_PRSNT_AMBER_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV35_PRSNT_AMBER_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV34_PRSNT_AMBER_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV33_PRSNT_AMBER_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV32_PRSNT_AMBER_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV3_IFDET_BLUE_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV2_IFDET_BLUE_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV1_IFDET_BLUE_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV0_IFDET_BLUE_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV7_IFDET_BLUE_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV6_IFDET_BLUE_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV5_IFDET_BLUE_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV4_IFDET_BLUE_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV11_IFDET_BLUE_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV10_IFDET_BLUE_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV9_IFDET_BLUE_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV8_IFDET_BLUE_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV15_IFDET_BLUE_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV14_IFDET_BLUE_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV13_IFDET_BLUE_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV12_IFDET_BLUE_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV19_IFDET_BLUE_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV18_IFDET_BLUE_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV17_IFDET_BLUE_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV16_IFDET_BLUE_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV23_IFDET_BLUE_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV22_IFDET_BLUE_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV21_IFDET_BLUE_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV20_IFDET_BLUE_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV27_IFDET_BLUE_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV26_IFDET_BLUE_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV25_IFDET_BLUE_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV24_IFDET_BLUE_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV31_IFDET_BLUE_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV30_IFDET_BLUE_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV29_IFDET_BLUE_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV28_IFDET_BLUE_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV35_IFDET_BLUE_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV34_IFDET_BLUE_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV33_IFDET_BLUE_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV32_IFDET_BLUE_LED
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV3_RST_DRV0_A_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV2_RST_DRV0_A_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV1_RST_DRV0_A_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV0_RST_DRV0_A_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV7_RST_DRV0_A_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV6_RST_DRV0_A_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV5_RST_DRV0_A_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV4_RST_DRV0_A_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV11_RST_DRV0_A_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV10_RST_DRV0_A_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV9_RST_DRV0_A_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV8_RST_DRV0_A_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV15_RST_DRV0_A_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV14_RST_DRV0_A_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV13_RST_DRV0_A_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV12_RST_DRV0_A_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV19_RST_DRV0_A_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV18_RST_DRV0_A_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV17_RST_DRV0_A_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV16_RST_DRV0_A_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV23_RST_DRV0_A_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV22_RST_DRV0_A_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV21_RST_DRV0_A_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV20_RST_DRV0_A_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV3_RST_DRV0_B_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV2_RST_DRV0_B_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV1_RST_DRV0_B_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV0_RST_DRV0_B_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV7_RST_DRV0_B_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV6_RST_DRV0_B_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV5_RST_DRV0_B_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV4_RST_DRV0_B_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV11_RST_DRV0_B_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV10_RST_DRV0_B_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV9_RST_DRV0_B_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV8_RST_DRV0_B_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV15_RST_DRV0_B_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV14_RST_DRV0_B_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV13_RST_DRV0_B_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV12_RST_DRV0_B_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV19_RST_DRV0_B_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV18_RST_DRV0_B_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV17_RST_DRV0_B_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV16_RST_DRV0_B_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV23_RST_DRV0_B_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV22_RST_DRV0_B_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV21_RST_DRV0_B_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV20_RST_DRV0_B_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV3_PCIE_CLK_A_OE_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV2_PCIE_CLK_A_OE_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV1_PCIE_CLK_A_OE_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV0_PCIE_CLK_A_OE_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV7_PCIE_CLK_A_OE_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV6_PCIE_CLK_A_OE_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV5_PCIE_CLK_A_OE_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV4_PCIE_CLK_A_OE_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV11_PCIE_CLK_A_OE_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV10_PCIE_CLK_A_OE_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV9_PCIE_CLK_A_OE_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV8_PCIE_CLK_A_OE_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV15_PCIE_CLK_A_OE_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV14_PCIE_CLK_A_OE_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV13_PCIE_CLK_A_OE_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV12_PCIE_CLK_A_OE_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV19_PCIE_CLK_A_OE_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV18_PCIE_CLK_A_OE_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV17_PCIE_CLK_A_OE_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV16_PCIE_CLK_A_OE_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV23_PCIE_CLK_A_OE_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV22_PCIE_CLK_A_OE_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV21_PCIE_CLK_A_OE_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV20_PCIE_CLK_A_OE_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV3_PCIE_CLK_B_OE_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV2_PCIE_CLK_B_OE_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV1_PCIE_CLK_B_OE_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV0_PCIE_CLK_B_OE_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV7_PCIE_CLK_B_OE_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV6_PCIE_CLK_B_OE_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV5_PCIE_CLK_B_OE_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV4_PCIE_CLK_B_OE_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV11_PCIE_CLK_B_OE_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV10_PCIE_CLK_B_OE_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV9_PCIE_CLK_B_OE_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV8_PCIE_CLK_B_OE_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV15_PCIE_CLK_B_OE_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV14_PCIE_CLK_B_OE_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV13_PCIE_CLK_B_OE_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV12_PCIE_CLK_B_OE_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV19_PCIE_CLK_B_OE_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV18_PCIE_CLK_B_OE_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV17_PCIE_CLK_B_OE_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV16_PCIE_CLK_B_OE_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV23_PCIE_CLK_B_OE_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV22_PCIE_CLK_B_OE_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV21_PCIE_CLK_B_OE_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV20_PCIE_CLK_B_OE_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/BB_CPLD_ALT_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/CANISTER_A_PCIE_CLK_ACT_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/CANISTER_B_PCIE_CLK_ACT_L
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/CPLD_SLOT_ID
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/STATUS_BOARD_PRSENT
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/SGPIO_CK
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/SGPIO_LD
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/SGPIO_DATA
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/I2C_DOUT_1
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/PORT_CS_1
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/OFFSET_SEL_1
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/RD_WR_1
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DIN_0_1
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DIN_1_1
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DIN_2_1
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DIN_3_1
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DIN_4_1
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DIN_5_1
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DIN_6_1
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DIN_7_1
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DIN_8_1
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DIN_9_1
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DIN_A_1
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DIN_B_1
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DIN_C_1
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DIN_D_1
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DIN_E_1
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DIN_F_1
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/WR_EN_1
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/I2C_DOUT_2
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/PORT_CS_2
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/OFFSET_SEL_2
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/RD_WR_2
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DIN_0_2
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DIN_1_2
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DIN_2_2
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DIN_3_2
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DIN_4_2
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DIN_5_2
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DIN_6_2
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DIN_7_2
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DIN_8_2
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DIN_9_2
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DIN_A_2
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DIN_B_2
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DIN_C_2
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DIN_D_2
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DIN_E_2
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DIN_F_2
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/WR_EN_2
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/LED_REG0
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/LED_REG1
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/LED_REG2
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/LED_REG3
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/LED_REG4
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/LED_REG5
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/LED_REG6
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/LED_REG7
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/PRSNT
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/IDENT
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/AMBER_DAT
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/BLUE_DAT
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/SCL_1
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/SDA_1
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/I2C_ADDRESS
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/SCL_2
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/SDA_2
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV_PWR_EN0
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV_PWR_EN1
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV_PWR_EN2
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV_PWR_EN3
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/DRV_PWR_EN4
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/FLT_AMB_LED0
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/FLT_AMB_LED1
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/FLT_AMB_LED2
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/FLT_AMB_LED3
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/FLT_AMB_LED4
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/FLT_AMB_LED5
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/FLT_AMB_LED6
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/FLT_AMB_LED7
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/FLT_AMB_LED8
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/FLT_AMB_LED9
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/FLT_AMB_LED10
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/FLT_AMB_LED11
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/FLT_AMB_LED12
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/FLT_AMB_LED13
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/FLT_AMB_LED14
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/FLT_AMB_LED15
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/FLT_AMB_LED16
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/FLT_AMB_LED17
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/IFDET_BLUE_LED0
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/IFDET_BLUE_LED1
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/IFDET_BLUE_LED2
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/IFDET_BLUE_LED3
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/IFDET_BLUE_LED4
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/IFDET_BLUE_LED5
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/IFDET_BLUE_LED6
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/IFDET_BLUE_LED7
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/IFDET_BLUE_LED8
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/IFDET_BLUE_LED9
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/IFDET_BLUE_LED10
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/IFDET_BLUE_LED11
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/IFDET_BLUE_LED12
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/IFDET_BLUE_LED13
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/IFDET_BLUE_LED14
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/IFDET_BLUE_LED15
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/IFDET_BLUE_LED16
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/IFDET_BLUE_LED17
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/CLK_1HZ
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/CLK_2HZ
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/CLK_4HZ
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/CLK_4HZ_500MS
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/CLK_4HZ_3500MS
add wave -noupdate -group BB_TOP_INST /tb_baseboard/BB_TOP_INST/CLK_07S
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/SCL
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/I2C_RESET_N
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/SYSCLK
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/DIN_0
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/DIN_1
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/DIN_2
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/DIN_3
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/DIN_4
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/DIN_5
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/DIN_6
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/DIN_7
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/DIN_8
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/DIN_9
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/DIN_A
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/DIN_B
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/DIN_C
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/DIN_D
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/DIN_E
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/DIN_F
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/I2C_ADDRESS
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/RD_WR
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/DOUT
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/PORT_CS
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/OFFSET_SEL
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/SDA
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/TIMER_OVFLOW
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/TIMER_CLR_N
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/STATE
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/START
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/STOP
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/SCL_D1
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/SCL_D2
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/SCL_PCLK
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/SCL_NCLK
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/SCL_PCLKD1
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/SCL_PCLKD2
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/SCL_PCLKD3
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/SDA_D1
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/SDA_D2
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/SDA_PCLK
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/SDA_NCLK
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/SDA_OUT
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/SDA_OE
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/NEXT_STATE
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/NEXT_STATE_D1
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/NEXT_STATE_D2
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/CNT
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/CNT8
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/CNT9
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/ADD_OK
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/LOC
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/WR_EN
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/WR_END1
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/WR_END2
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/RD_EN
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/RD_END1
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/RD_END2
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/RD_END3
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/PORT_CSD1
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/PORT_CSD2
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/SHIFT_DIN
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/REG_DIN
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/SHIFT_DOUT
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/CHECKSUM_IN
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/MASTER_RD_NACK
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/I2C_NACK
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/RESET_N
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/SCL_PCLK_W
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/SCL_NCLK_W
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/SDA_PCLK_W
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/SDA_NCLK_W
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/CNT0_W
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/CNT7_W
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/CNT8_W
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/CNT9_W
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/NEXT_STATE_W
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/START_W
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/STOP_W
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/I2C_CHECKSUM_SEL
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/CHECKSUM_RESULT
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/CHECKSUM_OUT
add wave -noupdate -group I2C_INS_1 /tb_baseboard/BB_TOP_INST/I2C_INS_1/PORT_W
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/SCL
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/I2C_RESET_N
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/SYSCLK
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/DIN_0
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/DIN_1
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/DIN_2
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/DIN_3
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/DIN_4
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/DIN_5
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/DIN_6
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/DIN_7
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/DIN_8
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/DIN_9
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/DIN_A
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/DIN_B
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/DIN_C
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/DIN_D
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/DIN_E
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/DIN_F
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/I2C_ADDRESS
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/RD_WR
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/DOUT
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/PORT_CS
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/OFFSET_SEL
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/SDA
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/TIMER_OVFLOW
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/TIMER_CLR_N
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/STATE
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/START
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/STOP
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/SCL_D1
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/SCL_D2
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/SCL_PCLK
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/SCL_NCLK
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/SCL_PCLKD1
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/SCL_PCLKD2
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/SCL_PCLKD3
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/SDA_D1
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/SDA_D2
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/SDA_PCLK
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/SDA_NCLK
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/SDA_OUT
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/SDA_OE
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/NEXT_STATE
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/NEXT_STATE_D1
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/NEXT_STATE_D2
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/CNT
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/CNT8
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/CNT9
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/ADD_OK
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/LOC
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/WR_EN
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/WR_END1
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/WR_END2
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/RD_EN
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/RD_END1
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/RD_END2
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/RD_END3
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/PORT_CSD1
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/PORT_CSD2
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/SHIFT_DIN
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/REG_DIN
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/SHIFT_DOUT
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/CHECKSUM_IN
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/MASTER_RD_NACK
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/I2C_NACK
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/RESET_N
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/SCL_PCLK_W
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/SCL_NCLK_W
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/SDA_PCLK_W
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/SDA_NCLK_W
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/CNT0_W
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/CNT7_W
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/CNT8_W
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/CNT9_W
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/NEXT_STATE_W
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/START_W
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/STOP_W
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/I2C_CHECKSUM_SEL
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/CHECKSUM_RESULT
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/CHECKSUM_OUT
add wave -noupdate -group I2C_INS_2 /tb_baseboard/BB_TOP_INST/I2C_INS_2/PORT_W
add wave -noupdate -group BB_SGPIO_INST /tb_baseboard/BB_TOP_INST/BB_SGPIO_INST/SYSCLK
add wave -noupdate -group BB_SGPIO_INST /tb_baseboard/BB_TOP_INST/BB_SGPIO_INST/RESET_N
add wave -noupdate -group BB_SGPIO_INST /tb_baseboard/BB_TOP_INST/BB_SGPIO_INST/DRV3_ACT_LED
add wave -noupdate -group BB_SGPIO_INST /tb_baseboard/BB_TOP_INST/BB_SGPIO_INST/DRV2_ACT_LED
add wave -noupdate -group BB_SGPIO_INST /tb_baseboard/BB_TOP_INST/BB_SGPIO_INST/DRV1_ACT_LED
add wave -noupdate -group BB_SGPIO_INST /tb_baseboard/BB_TOP_INST/BB_SGPIO_INST/DRV0_ACT_LED
add wave -noupdate -group BB_SGPIO_INST /tb_baseboard/BB_TOP_INST/BB_SGPIO_INST/DRV7_ACT_LED
add wave -noupdate -group BB_SGPIO_INST /tb_baseboard/BB_TOP_INST/BB_SGPIO_INST/DRV6_ACT_LED
add wave -noupdate -group BB_SGPIO_INST /tb_baseboard/BB_TOP_INST/BB_SGPIO_INST/DRV5_ACT_LED
add wave -noupdate -group BB_SGPIO_INST /tb_baseboard/BB_TOP_INST/BB_SGPIO_INST/DRV4_ACT_LED
add wave -noupdate -group BB_SGPIO_INST /tb_baseboard/BB_TOP_INST/BB_SGPIO_INST/DRV11_ACT_LED
add wave -noupdate -group BB_SGPIO_INST /tb_baseboard/BB_TOP_INST/BB_SGPIO_INST/DRV10_ACT_LED
add wave -noupdate -group BB_SGPIO_INST /tb_baseboard/BB_TOP_INST/BB_SGPIO_INST/DRV9_ACT_LED
add wave -noupdate -group BB_SGPIO_INST /tb_baseboard/BB_TOP_INST/BB_SGPIO_INST/DRV8_ACT_LED
add wave -noupdate -group BB_SGPIO_INST /tb_baseboard/BB_TOP_INST/BB_SGPIO_INST/DRV15_ACT_LED
add wave -noupdate -group BB_SGPIO_INST /tb_baseboard/BB_TOP_INST/BB_SGPIO_INST/DRV14_ACT_LED
add wave -noupdate -group BB_SGPIO_INST /tb_baseboard/BB_TOP_INST/BB_SGPIO_INST/DRV13_ACT_LED
add wave -noupdate -group BB_SGPIO_INST /tb_baseboard/BB_TOP_INST/BB_SGPIO_INST/DRV12_ACT_LED
add wave -noupdate -group BB_SGPIO_INST /tb_baseboard/BB_TOP_INST/BB_SGPIO_INST/DRV19_ACT_LED
add wave -noupdate -group BB_SGPIO_INST /tb_baseboard/BB_TOP_INST/BB_SGPIO_INST/DRV18_ACT_LED
add wave -noupdate -group BB_SGPIO_INST /tb_baseboard/BB_TOP_INST/BB_SGPIO_INST/DRV17_ACT_LED
add wave -noupdate -group BB_SGPIO_INST /tb_baseboard/BB_TOP_INST/BB_SGPIO_INST/DRV16_ACT_LED
add wave -noupdate -group BB_SGPIO_INST /tb_baseboard/BB_TOP_INST/BB_SGPIO_INST/DRV23_ACT_LED
add wave -noupdate -group BB_SGPIO_INST /tb_baseboard/BB_TOP_INST/BB_SGPIO_INST/DRV22_ACT_LED
add wave -noupdate -group BB_SGPIO_INST /tb_baseboard/BB_TOP_INST/BB_SGPIO_INST/DRV21_ACT_LED
add wave -noupdate -group BB_SGPIO_INST /tb_baseboard/BB_TOP_INST/BB_SGPIO_INST/DRV20_ACT_LED
add wave -noupdate -group BB_SGPIO_INST /tb_baseboard/BB_TOP_INST/BB_SGPIO_INST/DRV27_ACT_LED
add wave -noupdate -group BB_SGPIO_INST /tb_baseboard/BB_TOP_INST/BB_SGPIO_INST/DRV26_ACT_LED
add wave -noupdate -group BB_SGPIO_INST /tb_baseboard/BB_TOP_INST/BB_SGPIO_INST/DRV25_ACT_LED
add wave -noupdate -group BB_SGPIO_INST /tb_baseboard/BB_TOP_INST/BB_SGPIO_INST/DRV24_ACT_LED
add wave -noupdate -group BB_SGPIO_INST /tb_baseboard/BB_TOP_INST/BB_SGPIO_INST/DRV31_ACT_LED
add wave -noupdate -group BB_SGPIO_INST /tb_baseboard/BB_TOP_INST/BB_SGPIO_INST/DRV30_ACT_LED
add wave -noupdate -group BB_SGPIO_INST /tb_baseboard/BB_TOP_INST/BB_SGPIO_INST/DRV29_ACT_LED
add wave -noupdate -group BB_SGPIO_INST /tb_baseboard/BB_TOP_INST/BB_SGPIO_INST/DRV28_ACT_LED
add wave -noupdate -group BB_SGPIO_INST /tb_baseboard/BB_TOP_INST/BB_SGPIO_INST/DRV35_ACT_LED
add wave -noupdate -group BB_SGPIO_INST /tb_baseboard/BB_TOP_INST/BB_SGPIO_INST/DRV34_ACT_LED
add wave -noupdate -group BB_SGPIO_INST /tb_baseboard/BB_TOP_INST/BB_SGPIO_INST/DRV33_ACT_LED
add wave -noupdate -group BB_SGPIO_INST /tb_baseboard/BB_TOP_INST/BB_SGPIO_INST/DRV32_ACT_LED
add wave -noupdate -group BB_SGPIO_INST /tb_baseboard/BB_TOP_INST/BB_SGPIO_INST/SGPIO_CK
add wave -noupdate -group BB_SGPIO_INST /tb_baseboard/BB_TOP_INST/BB_SGPIO_INST/SGPIO_LD
add wave -noupdate -group BB_SGPIO_INST /tb_baseboard/BB_TOP_INST/BB_SGPIO_INST/SGPIO_DATA
add wave -noupdate -group BB_SGPIO_INST /tb_baseboard/BB_TOP_INST/BB_SGPIO_INST/ACT_LED
add wave -noupdate -group BB_SGPIO_INST /tb_baseboard/BB_TOP_INST/BB_SGPIO_INST/ACT_LED_TMP
add wave -noupdate -group BB_SGPIO_INST /tb_baseboard/BB_TOP_INST/BB_SGPIO_INST/STATE
add wave -noupdate -group BB_SGPIO_INST /tb_baseboard/BB_TOP_INST/BB_SGPIO_INST/HDD_CNT
add wave -noupdate -group BB_SGPIO_INST /tb_baseboard/BB_TOP_INST/BB_SGPIO_INST/SGPIO_CK_D3
add wave -noupdate -group BB_SGPIO_INST /tb_baseboard/BB_TOP_INST/BB_SGPIO_INST/SGPIO_CK_D2
add wave -noupdate -group BB_SGPIO_INST /tb_baseboard/BB_TOP_INST/BB_SGPIO_INST/SGPIO_CK_D1
add wave -noupdate -group BB_SGPIO_INST /tb_baseboard/BB_TOP_INST/BB_SGPIO_INST/CNT
add wave -noupdate -group BB_SGPIO_INST /tb_baseboard/BB_TOP_INST/BB_SGPIO_INST/TIME_OUT
add wave -noupdate -group BB_SGPIO_INST /tb_baseboard/BB_TOP_INST/BB_SGPIO_INST/SGPIO_CK_P
add wave -noupdate -group BB_SGPIO_INST /tb_baseboard/BB_TOP_INST/BB_SGPIO_INST/SGPIO_CK_N
add wave -noupdate -group STATUS_SGPIO_INST1 /tb_baseboard/STATUS_INST/SGPIO_INST1/SYSCLK
add wave -noupdate -group STATUS_SGPIO_INST1 /tb_baseboard/STATUS_INST/SGPIO_INST1/RESET_N
add wave -noupdate -group STATUS_SGPIO_INST1 /tb_baseboard/STATUS_INST/SGPIO_INST1/SCLK
add wave -noupdate -group STATUS_SGPIO_INST1 /tb_baseboard/STATUS_INST/SGPIO_INST1/SLOAD
add wave -noupdate -group STATUS_SGPIO_INST1 /tb_baseboard/STATUS_INST/SGPIO_INST1/SDOUT
add wave -noupdate -group STATUS_SGPIO_INST1 /tb_baseboard/STATUS_INST/SGPIO_INST1/ACT_LED
add wave -noupdate -group STATUS_SGPIO_INST1 /tb_baseboard/STATUS_INST/SGPIO_INST1/FLT_LED
add wave -noupdate -group STATUS_SGPIO_INST1 /tb_baseboard/STATUS_INST/SGPIO_INST1/ACT_LED_TMP
add wave -noupdate -group STATUS_SGPIO_INST1 /tb_baseboard/STATUS_INST/SGPIO_INST1/FLT_LED_TMP
add wave -noupdate -group STATUS_SGPIO_INST1 /tb_baseboard/STATUS_INST/SGPIO_INST1/STATE
add wave -noupdate -group STATUS_SGPIO_INST1 /tb_baseboard/STATUS_INST/SGPIO_INST1/HDD_CNT
add wave -noupdate -group STATUS_SGPIO_INST1 /tb_baseboard/STATUS_INST/SGPIO_INST1/SCLK_D1
add wave -noupdate -group STATUS_SGPIO_INST1 /tb_baseboard/STATUS_INST/SGPIO_INST1/SCLK_D2
add wave -noupdate -group STATUS_SGPIO_INST1 /tb_baseboard/STATUS_INST/SGPIO_INST1/SCLK_D3
add wave -noupdate -group STATUS_SGPIO_INST1 /tb_baseboard/STATUS_INST/SGPIO_INST1/CNT
add wave -noupdate -group STATUS_SGPIO_INST1 /tb_baseboard/STATUS_INST/SGPIO_INST1/TIME_OUT
add wave -noupdate -group STATUS_SGPIO_INST1 /tb_baseboard/STATUS_INST/SGPIO_INST1/SCLK_P
add wave -noupdate -group STATUS_SGPIO_INST1 /tb_baseboard/STATUS_INST/SGPIO_INST1/SCLK_N
add wave -noupdate -group STATUS_SGPIO_INST1 /tb_baseboard/STATUS_INST/SGPIO_INST1/FRM_STAT
add wave -noupdate -group STATUS_SGPIO_INST2 /tb_baseboard/STATUS_INST/SGPIO_INST2/SYSCLK
add wave -noupdate -group STATUS_SGPIO_INST2 /tb_baseboard/STATUS_INST/SGPIO_INST2/RESET_N
add wave -noupdate -group STATUS_SGPIO_INST2 /tb_baseboard/STATUS_INST/SGPIO_INST2/SCLK
add wave -noupdate -group STATUS_SGPIO_INST2 /tb_baseboard/STATUS_INST/SGPIO_INST2/SLOAD
add wave -noupdate -group STATUS_SGPIO_INST2 /tb_baseboard/STATUS_INST/SGPIO_INST2/SDOUT
add wave -noupdate -group STATUS_SGPIO_INST2 /tb_baseboard/STATUS_INST/SGPIO_INST2/ACT_LED
add wave -noupdate -group STATUS_SGPIO_INST2 /tb_baseboard/STATUS_INST/SGPIO_INST2/FLT_LED
add wave -noupdate -group STATUS_SGPIO_INST2 /tb_baseboard/STATUS_INST/SGPIO_INST2/ACT_LED_TMP
add wave -noupdate -group STATUS_SGPIO_INST2 /tb_baseboard/STATUS_INST/SGPIO_INST2/FLT_LED_TMP
add wave -noupdate -group STATUS_SGPIO_INST2 /tb_baseboard/STATUS_INST/SGPIO_INST2/STATE
add wave -noupdate -group STATUS_SGPIO_INST2 /tb_baseboard/STATUS_INST/SGPIO_INST2/HDD_CNT
add wave -noupdate -group STATUS_SGPIO_INST2 /tb_baseboard/STATUS_INST/SGPIO_INST2/SCLK_D1
add wave -noupdate -group STATUS_SGPIO_INST2 /tb_baseboard/STATUS_INST/SGPIO_INST2/SCLK_D2
add wave -noupdate -group STATUS_SGPIO_INST2 /tb_baseboard/STATUS_INST/SGPIO_INST2/SCLK_D3
add wave -noupdate -group STATUS_SGPIO_INST2 /tb_baseboard/STATUS_INST/SGPIO_INST2/CNT
add wave -noupdate -group STATUS_SGPIO_INST2 /tb_baseboard/STATUS_INST/SGPIO_INST2/TIME_OUT
add wave -noupdate -group STATUS_SGPIO_INST2 /tb_baseboard/STATUS_INST/SGPIO_INST2/SCLK_P
add wave -noupdate -group STATUS_SGPIO_INST2 /tb_baseboard/STATUS_INST/SGPIO_INST2/SCLK_N
add wave -noupdate -group STATUS_SGPIO_INST2 /tb_baseboard/STATUS_INST/SGPIO_INST2/FRM_STAT
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {3457351 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 156
configure wave -valuecolwidth 98
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ns} {5857677 ns}
